---
version: '2'
services:
  gemserver:
    build: .
    environment:
      - GEMINABOX_USER=${GEMINABOX_USER}
      - GEMINABOX_PASS=${GEMINABOX_PASS}
      - RUBYGEMS_PROXY=true
    volumes:
      - /var/data
    ports:
     - "127.0.0.1:9292:9292"
